// SPDX-License-Identifier: GPL-3.0-or-later
import Foundation

/// What the clipboard history leaves out.
public enum ClipboardPolicy {
    /// Pasteboard types that password managers and clipboard tools add to
    /// copies that shouldn't be kept (see nspasteboard.org).
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "Pasteboard generator type",
    ]

    /// Apps whose copies are never recorded, marked or not: password managers
    /// and the keychain.
    public static let ignoredApps: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.apple.keychainaccess", "com.apple.Passwords",
        "com.lastpass.LastPass", "in.sinew.Enpass-Desktop", "com.dashlane.Dashlane", "org.keepassxc.keepassxc",
    ]

    /// Terminals, left out only when Settings asks for it.
    public static let terminalApps: Set<String> = [
        "com.apple.Terminal", "com.mitchellh.ghostty", "com.googlecode.iterm2", "dev.warp.Warp-Stable",
        "net.kovidgoyal.kitty", "org.alacritty", "co.zeit.hyper", "dev.zed.Zed",
    ]

    /// Credentials with a recognisable shape. Any of these anywhere in a copy
    /// (a line of a .env file, say) keeps the whole copy out.
    private static let credentialPatterns: [NSRegularExpression] = [
        #"sk-(?:ant-|proj-)?[A-Za-z0-9_\-]{20,}"#,                       // OpenAI, Anthropic
        #"\b(?:gh[pousr]_[A-Za-z0-9]{36,}|github_pat_[A-Za-z0-9_]{40,})\b"#, // GitHub
        #"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b"#,                                // AWS access key
        #"\bxox[abprs]-[A-Za-z0-9\-]{10,}\b"#,                            // Slack
        #"\bAIza[0-9A-Za-z_\-]{35}\b"#,                                   // Google API
        #"\b[rs]k_live_[0-9A-Za-z]{20,}\b"#,                              // Stripe
        #"\beyJ[A-Za-z0-9_\-]{10,}\.eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}"#, // JWT
        #"-----BEGIN [A-Z ]*PRIVATE KEY-----"#,                          // PEM private key
        // A key = "literal" line; `token = getToken()` and the like are code, not secrets.
        #"(?im)\b(?:password|passwd|secret|api[_-]?key|access[_-]?key|token)\s*[:=]\s*["']?[A-Za-z0-9_\-+/=.]{12,}["']?\s*$"#,
    ].map { try! NSRegularExpression(pattern: $0) }

    private static let uuid = try! NSRegularExpression(
        pattern: #"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"#)

    /// Whether a copy looks like a password, key or token. Besides the known
    /// shapes, a single long run of letters and digits counts, as random keys
    /// look like that; ids that are common to copy (UUIDs, git hashes) don't.
    public static func looksSecret(_ text: String) -> Bool {
        let range = NSRange(text.startIndex..., in: text)
        if credentialPatterns.contains(where: { $0.firstMatch(in: text, range: range) != nil }) { return true }

        let token = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard token.count >= 32, token.count <= 256, !token.contains(where: \.isWhitespace) else { return false }
        if token.contains("://") || token.hasPrefix("/") || token.hasPrefix("~") { return false }   // links and paths
        if uuid.firstMatch(in: token, range: NSRange(token.startIndex..., in: token)) != nil { return false }
        if token.count == 40, token.allSatisfy({ $0.isHexDigit && !$0.isUppercase }) { return false } // git commit
        let letters = token.contains(where: \.isLetter)
        let digits = token.contains(where: \.isNumber)
        let symbolsOnlyFromKeys = token.allSatisfy { $0.isLetter || $0.isNumber || "-_+/=.".contains($0) }
        return letters && digits && symbolsOnlyFromKeys
    }
}
