// SPDX-License-Identifier: GPL-3.0-or-later
import AppKit
import CryptoKit

/// One thing that was on the clipboard, or one upload to R2.
struct ClipboardEntry: Codable, Identifiable, Equatable {
    enum Kind: String, Codable {
        case text, image, files, upload
    }

    let id: UUID
    var kind: Kind
    var date: Date
    /// The text; copied files' paths, one per line; the link an upload copied.
    var text: String
    /// What makes two entries the same: the text, an image's hash, an upload's URL.
    var fingerprint: String
    /// The app that was in front when it was copied.
    var sourceApp: String?
    var url: String?
    var filename: String?
    var width: Int?
    var height: Int?

    init(kind: Kind, text: String, fingerprint: String, sourceApp: String? = nil) {
        id = UUID()
        self.kind = kind
        date = Date()
        self.text = text
        self.fingerprint = fingerprint
        self.sourceApp = sourceApp
    }

    var paths: [String] { kind == .files ? text.components(separatedBy: "\n") : [] }

    /// A line for lists and menus.
    var title: String {
        switch kind {
        case .text:
            return text.split(whereSeparator: \.isNewline).lazy
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .first { !$0.isEmpty } ?? text
        case .image:
            if let width, let height { return "Image \(width) × \(height)" }
            return "Image"
        case .files:
            let paths = paths
            return paths.count == 1 ? (paths[0] as NSString).lastPathComponent : "\(paths.count) Files"
        case .upload:
            return filename ?? url ?? text
        }
    }
}

/// What has been copied on this Mac, newest first, and every upload to R2.
/// Kept in Application Support: an index plus the images, each beside a
/// small thumbnail for the lists.
@MainActor
final class ClipboardHistory: ObservableObject {
    static let shared = ClipboardHistory()

    static let enabledKey = "clipboardHistory.enabled"
    static let limitKey = "clipboardHistory.limit"
    static let limits = [50, 100, 200, 500]

    static let directory = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        .appendingPathComponent("R2Drop/Clipboard")
    private static let indexURL = directory.appendingPathComponent("history.json")

    /// Longer copies are cut short; images bigger than this are skipped.
    private static let maxTextLength = 100_000
    private static let maxImageBytes = 40_000_000

    /// Password managers and clipboard tools mark copies that shouldn't be
    /// kept (see nspasteboard.org); those are never recorded.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType", "Pasteboard generator type",
    ]

    @Published private(set) var entries: [ClipboardEntry] = []

    private let pasteboard = NSPasteboard.general
    private var changeCount = NSPasteboard.general.changeCount
    private var timer: Timer?

    var isRecording: Bool { UserDefaults.standard.object(forKey: Self.enabledKey) as? Bool ?? true }

    var limit: Int {
        let stored = UserDefaults.standard.integer(forKey: Self.limitKey)
        return stored > 0 ? stored : 200
    }

    private init() {
        load()
    }

    /// macOS has no notification for clipboard changes, so the change count
    /// is polled, as every clipboard manager does.
    func start() {
        timer?.invalidate()
        changeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Called right after R2Drop writes the clipboard itself, so the write
    /// isn't recorded as a copy.
    func ignoreCurrentClipboard() {
        changeCount = pasteboard.changeCount
    }

    private func poll() {
        guard pasteboard.changeCount != changeCount else { return }
        changeCount = pasteboard.changeCount
        guard isRecording, let entry = readClipboard() else { return }
        insert(entry)
    }

    private func readClipboard() -> ClipboardEntry? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.ignoredTypes) else { return nil }
        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        let files = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []
        if !files.isEmpty {
            let paths = files.map(\.path).joined(separator: "\n")
            return ClipboardEntry(kind: .files, text: paths, fingerprint: "files:" + paths, sourceApp: source)
        }

        let string = pasteboard.string(forType: .string) ?? ""
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        // A browser copies an image with its address beside it, and an editor
        // can copy text with a picture of it: the image wins only in the first case.
        let isAddress = trimmed.isEmpty || (!trimmed.contains(where: \.isWhitespace) && URL(string: trimmed)?.scheme != nil)
        if isAddress, let image = readImage(source: source) {
            return image
        }
        guard !trimmed.isEmpty else { return nil }
        let text = String(string.prefix(Self.maxTextLength))
        return ClipboardEntry(kind: .text, text: text, fingerprint: "text:" + text, sourceApp: source)
    }

    private func readImage(source: String?) -> ClipboardEntry? {
        let png: Data?
        if let data = pasteboard.data(forType: .png) {
            png = data
        } else if let tiff = pasteboard.data(forType: .tiff), tiff.count <= Self.maxImageBytes {
            png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        } else {
            png = nil
        }
        guard let png, png.count <= Self.maxImageBytes, let image = NSImage(data: png),
              let rep = NSBitmapImageRep(data: png) else { return nil }
        let hash = SHA256.hash(data: png).map { String(format: "%02x", $0) }.joined()
        var entry = ClipboardEntry(kind: .image, text: "", fingerprint: "image:" + hash, sourceApp: source)
        entry.width = rep.pixelsWide
        entry.height = rep.pixelsHigh
        do {
            try FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
            try png.write(to: Self.imageURL(entry))
            try image.thumbnail(maxSide: 128)?.pngData?.write(to: Self.thumbnailURL(entry))
        } catch {
            Self.removeFiles(of: entry)
            return nil
        }
        return entry
    }

    /// Uploads are listed whether or not they touched the clipboard
    /// (Capture to BlogWatcher leaves it alone), and whether or not copies
    /// are being recorded.
    func recordUpload(_ result: UploadResult, link: String, image file: URL) {
        var entry = ClipboardEntry(kind: .upload, text: link, fingerprint: "upload:" + result.url)
        entry.url = result.url
        entry.filename = result.filename
        if let rep = NSImageRep(contentsOf: file) {
            entry.width = rep.pixelsWide
            entry.height = rep.pixelsHigh
        }
        try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
        try? NSImage(contentsOf: file)?.thumbnail(maxSide: 128)?.pngData?.write(to: Self.thumbnailURL(entry))
        insert(entry)
    }

    /// Puts an entry back on the clipboard and moves it to the top, as
    /// copying it again would.
    func copy(_ entry: ClipboardEntry) {
        pasteboard.clearContents()
        switch entry.kind {
        case .text, .upload:
            pasteboard.setString(entry.text, forType: .string)
        case .image:
            if let png = try? Data(contentsOf: Self.imageURL(entry)) {
                let item = NSPasteboardItem()
                item.setData(png, forType: .png)
                if let tiff = NSImage(data: png)?.tiffRepresentation {
                    item.setData(tiff, forType: .tiff)
                }
                pasteboard.writeObjects([item])
            }
        case .files:
            pasteboard.writeObjects(entry.paths.map { NSURL(fileURLWithPath: $0) })
        }
        ignoreCurrentClipboard()
        if let index = entries.firstIndex(where: { $0.id == entry.id }) {
            var moved = entries.remove(at: index)
            moved.date = Date()
            entries.insert(moved, at: 0)
            save()
        }
    }

    func delete(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        Self.removeFiles(of: entry)
        save()
    }

    func clear() {
        entries = []
        try? FileManager.default.removeItem(at: Self.directory)
    }

    /// Drops the oldest entries past the limit set in Settings.
    func trim() {
        guard entries.count > limit else { return }
        for entry in entries[limit...] {
            Self.removeFiles(of: entry)
        }
        entries.removeLast(entries.count - limit)
        save()
    }

    private func insert(_ entry: ClipboardEntry) {
        if let index = entries.firstIndex(where: { $0.fingerprint == entry.fingerprint }) {
            Self.removeFiles(of: entries.remove(at: index))
        }
        entries.insert(entry, at: 0)
        trim()
        save()
    }

    // MARK: Storage

    static func imageURL(_ entry: ClipboardEntry) -> URL {
        directory.appendingPathComponent("\(entry.id.uuidString).png")
    }

    static func thumbnailURL(_ entry: ClipboardEntry) -> URL {
        directory.appendingPathComponent("\(entry.id.uuidString)-thumb.png")
    }

    static func thumbnail(_ entry: ClipboardEntry) -> NSImage? {
        NSImage(contentsOf: thumbnailURL(entry))
    }

    private static func removeFiles(of entry: ClipboardEntry) {
        try? FileManager.default.removeItem(at: imageURL(entry))
        try? FileManager.default.removeItem(at: thumbnailURL(entry))
    }

    private func load() {
        guard let data = try? Data(contentsOf: Self.indexURL),
              let saved = try? JSONDecoder().decode([ClipboardEntry].self, from: data) else { return }
        entries = saved.filter { $0.kind != .image || FileManager.default.fileExists(atPath: Self.imageURL($0).path) }
    }

    private func save() {
        guard let data = try? JSONEncoder().encode(entries) else { return }
        try? FileManager.default.createDirectory(at: Self.directory, withIntermediateDirectories: true)
        try? data.write(to: Self.indexURL, options: .atomic)
    }
}

extension NSImage {
    var pngData: Data? {
        guard let tiff = tiffRepresentation else { return nil }
        return NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
    }
}
